subscription_id                      = "00000000-0000-0000-0000-000000000000"
location                             = "eastus"
workload                             = "chatbot"
environment                          = "prod"
resource_group_name                  = "rg-enterprise-ai-chatbot-prod"
app_service_plan_name                = "asp-enterprise-ai-chatbot-prod"
app_service_name                     = "app-enterprise-ai-chatbot-prod"
app_registration_display_name        = "appreg-enterprise-ai-chatbot-prod"
app_service_python_version           = "3.14"
app_service_enable_auth              = false
landingzone_resource_group_name      = "TODO-rg-platform-prod"
landingzone_ai_resource_group_name   = "TODO-rg-platform-prod"
landingzone_storage_account_name     = "TODO-storage-account-name"
landingzone_key_vault_name           = "TODO-key-vault-name"
landingzone_openai_name              = "TODO-openai-name"
landingzone_openai_enabled           = false
landingzone_azure_ai_service_name    = "TODO-azure-ai-service-name"
landingzone_azure_ai_service_enabled = false
landingzone_azure_ai_search_name     = "TODO-azure-ai-search-name"
landingzone_azure_ai_search_enabled  = false
landingzone_log_analytics_name       = "TODO-log-analytics-name"

rg_tags = {
  "Application Name"                  = "CCOE INFRA IAC"
  "Application Owner"                 = "CCOE"
  "AppSupport Team"                   = "CCOE"
  "Approval Group"                    = "CCOE"
  "Business Owner"                    = "CCOE"
  "Environment"                       = "Prod"
  "Infra Availability Classification" = "Bronze"
  "InfraSupport Team"                 = "CCOE"
  "Maintenance Window"                = "CCOE"
  "Project Name"                      = "CCOE INFRA IAC"
  "Project Number"                    = "N/A"
  "RPO-RTO"                           = "48H/24H"
  "Run Cost(Approved Run Budget)-USD" = "100"
}
